[2024-03-24T08:16:55.661+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:16:53.699046+00:00 [queued]>
[2024-03-24T08:16:55.663+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:16:53.699046+00:00 [queued]>
[2024-03-24T08:16:55.663+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-24T08:16:55.670+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): extract_data_from_web> on 2024-03-24 08:16:53.699046+00:00
[2024-03-24T08:16:55.674+0000] {standard_task_runner.py:60} INFO - Started process 1796 to run task
[2024-03-24T08:16:55.678+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'scrap_load_data_to_postgres', 'extract_data_from_web', 'manual__2024-03-24T08:16:53.699046+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/scrap_elt_.py', '--cfg-path', '/tmp/tmpo32i_b6f']
[2024-03-24T08:16:55.680+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask extract_data_from_web
[2024-03-24T08:16:55.702+0000] {task_command.py:423} INFO - Running <TaskInstance: scrap_load_data_to_postgres.extract_data_from_web manual__2024-03-24T08:16:53.699046+00:00 [running]> on host c112f9517df7
[2024-03-24T08:16:55.767+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scrap_load_data_to_postgres' AIRFLOW_CTX_TASK_ID='extract_data_from_web' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T08:16:53.699046+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-24T08:16:53.699046+00:00'
[2024-03-24T08:16:58.036+0000] {logging_mixin.py:188} INFO - Sukses!
[2024-03-24T08:16:58.099+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scrap_elt_.py", line 53, in extract_data_from_web
    item_pemain['kontrak'] = utils.extract_date(kontrak) if kontrak == "-" else kontrak
  File "/opt/airflow/dags/helpers/utils.py", line 52, in extract_date
    bulan_str = bulan_dict.get(tanggal_parts[1], tanggal_parts[1])
IndexError: list index out of range
[2024-03-24T08:16:58.103+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=scrap_load_data_to_postgres, task_id=extract_data_from_web, execution_date=20240324T081653, start_date=20240324T081655, end_date=20240324T081658
[2024-03-24T08:16:58.109+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 18 for task extract_data_from_web (list index out of range; 1796)
[2024-03-24T08:16:58.122+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-24T08:16:58.129+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
