[2024-03-23 08:58:55,815] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: load_data_to_postgres.load_to_postgres manual__2024-03-23T08:58:49.076949+00:00 [queued]>
[2024-03-23 08:58:55,818] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: load_data_to_postgres.load_to_postgres manual__2024-03-23T08:58:49.076949+00:00 [queued]>
[2024-03-23 08:58:55,818] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-03-23 08:58:55,818] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2024-03-23 08:58:55,818] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-03-23 08:58:55,824] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2024-03-23 08:58:49.076949+00:00
[2024-03-23 08:58:55,830] {standard_task_runner.py:52} INFO - Started process 925 to run task
[2024-03-23 08:58:55,832] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'load_data_to_postgres', 'load_to_postgres', 'manual__2024-03-23T08:58:49.076949+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_dbt.py', '--cfg-path', '/tmp/tmp62zbbyfp', '--error-file', '/tmp/tmpu0gvdern']
[2024-03-23 08:58:55,833] {standard_task_runner.py:80} INFO - Job 10: Subtask load_to_postgres
[2024-03-23 08:58:55,872] {task_command.py:371} INFO - Running <TaskInstance: load_data_to_postgres.load_to_postgres manual__2024-03-23T08:58:49.076949+00:00 [running]> on host 810364161d6b
[2024-03-23 08:58:55,901] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_data_to_postgres
AIRFLOW_CTX_TASK_ID=load_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2024-03-23T08:58:49.076949+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-23T08:58:49.076949+00:00
[2024-03-23 08:58:55,902] {logging_mixin.py:115} WARNING - --- Logging error ---
[2024-03-23 08:58:55,903] {logging_mixin.py:115} WARNING - Traceback (most recent call last):
[2024-03-23 08:58:55,903] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
[2024-03-23 08:58:55,903] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
[2024-03-23 08:58:55,903] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
[2024-03-23 08:58:55,903] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
[2024-03-23 08:58:55,903] {logging_mixin.py:115} WARNING - TypeError: not all arguments converted during string formatting
[2024-03-23 08:58:55,903] {logging_mixin.py:115} WARNING - Call stack:
[2024-03-23 08:58:55,905] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
[2024-03-23 08:58:55,905] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/__main__.py", line 38, in main
    args.func(args)
[2024-03-23 08:58:55,905] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 51, in command
    return func(*args, **kwargs)
[2024-03-23 08:58:55,905] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 99, in wrapper
    return f(*args, **kwargs)
[2024-03-23 08:58:55,905] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 377, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2024-03-23 08:58:55,905] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 183, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2024-03-23 08:58:55,906] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 241, in _run_task_by_local_task_job
    run_job.run()
[2024-03-23 08:58:55,906] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/base_job.py", line 244, in run
    self._execute()
[2024-03-23 08:58:55,906] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/local_task_job.py", line 105, in _execute
    self.task_runner.start()
[2024-03-23 08:58:55,906] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2024-03-23 08:58:55,906] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 88, in _start_by_fork
    args.func(args, dag=self.dag)
[2024-03-23 08:58:55,906] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 51, in command
    return func(*args, **kwargs)
[2024-03-23 08:58:55,906] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 99, in wrapper
    return f(*args, **kwargs)
[2024-03-23 08:58:55,906] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 377, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2024-03-23 08:58:55,906] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 185, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2024-03-23 08:58:55,906] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 262, in _run_raw_task
    error_file=args.error_file,
[2024-03-23 08:58:55,906] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
[2024-03-23 08:58:55,907] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1471, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
[2024-03-23 08:58:55,907] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1618, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2024-03-23 08:58:55,907] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1679, in _execute_task
    result = execute_callable(context=context)
[2024-03-23 08:58:55,907] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
[2024-03-23 08:58:55,907] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2024-03-23 08:58:55,907] {logging_mixin.py:115} WARNING -   File "/opt/airflow/dags/api_etl_dbt.py", line 56, in load_to_postgres
    logging.info(tbl_pemain, "tbl_pemain")
[2024-03-23 08:58:55,907] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1992, in info
    root.info(msg, *args, **kwargs)
[2024-03-23 08:58:55,907] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
[2024-03-23 08:58:55,907] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
[2024-03-23 08:58:55,907] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
[2024-03-23 08:58:55,907] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
[2024-03-23 08:58:55,907] {logging_mixin.py:115} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
[2024-03-23 08:58:55,908] {logging_mixin.py:115} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/log/file_task_handler.py", line 71, in emit
    self.handler.emit(record)
[2024-03-23 08:58:55,908] {logging_mixin.py:115} WARNING - Message: 'tbl_pemain'
Arguments: ('tbl_pemain',)
[2024-03-23 08:58:55,921] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api_etl_dbt.py", line 58, in load_to_postgres
    tbl_pemain.to_sql('tbl_pemain', engine, if_exists='replace', index=False)
AttributeError: 'str' object has no attribute 'to_sql'
[2024-03-23 08:58:55,923] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=load_data_to_postgres, task_id=load_to_postgres, execution_date=20240323T085849, start_date=20240323T085855, end_date=20240323T085855
[2024-03-23 08:58:55,927] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task load_to_postgres ('str' object has no attribute 'to_sql'; 925)
[2024-03-23 08:58:55,938] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-23 08:58:55,951] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
