[2024-03-24T22:18:28.369+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrap_load_data_to_postgres.dbt_run_model_1 manual__2024-03-24T22:18:17.508631+00:00 [queued]>
[2024-03-24T22:18:28.376+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrap_load_data_to_postgres.dbt_run_model_1 manual__2024-03-24T22:18:17.508631+00:00 [queued]>
[2024-03-24T22:18:28.377+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-24T22:18:28.392+0000] {taskinstance.py:2217} INFO - Executing <Task(DbtRunOperator): dbt_run_model_1> on 2024-03-24 22:18:17.508631+00:00
[2024-03-24T22:18:28.401+0000] {standard_task_runner.py:60} INFO - Started process 240 to run task
[2024-03-24T22:18:28.406+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'scrap_load_data_to_postgres', 'dbt_run_model_1', 'manual__2024-03-24T22:18:17.508631+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/scrap_elt_.py', '--cfg-path', '/tmp/tmpy3m9n_s2']
[2024-03-24T22:18:28.408+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask dbt_run_model_1
[2024-03-24T22:18:28.436+0000] {task_command.py:423} INFO - Running <TaskInstance: scrap_load_data_to_postgres.dbt_run_model_1 manual__2024-03-24T22:18:17.508631+00:00 [running]> on host 7f86ad096cb1
[2024-03-24T22:18:28.473+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scrap_load_data_to_postgres' AIRFLOW_CTX_TASK_ID='dbt_run_model_1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T22:18:17.508631+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-24T22:18:17.508631+00:00'
[2024-03-24T22:18:28.474+0000] {dbt_hook.py:117} INFO - dbt run --profiles-dir /opt/airflow/dbt/airflowdbt --select model_1
[2024-03-24T22:18:28.484+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 98, in execute
    self.create_hook().run_cli('run')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 119, in run_cli
    sp = subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'dbt'
[2024-03-24T22:18:28.526+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=scrap_load_data_to_postgres, task_id=dbt_run_model_1, execution_date=20240324T221817, start_date=20240324T221828, end_date=20240324T221828
[2024-03-24T22:18:28.557+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task dbt_run_model_1 ([Errno 13] Permission denied: 'dbt'; 240)
[2024-03-24T22:18:28.589+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-24T22:18:28.607+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
